ALTER TABLE leads ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE clientes ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE propostas ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE propostas ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE tarefas ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE tarefas ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE consents ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE simulations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
