ALTER TABLE leads ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS deleted_by INTEGER;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS deletion_reason TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS cpf_hash VARCHAR(64);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS cpf_encrypted TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS telefone_encrypted TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS email_encrypted TEXT;

ALTER TABLE clientes ADD COLUMN IF NOT EXISTS deleted_by INTEGER;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS deletion_reason TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS cpf_hash VARCHAR(64);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS cpf_encrypted TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS telefone_encrypted TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS email_encrypted TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS bank_data_encrypted TEXT;

ALTER TABLE propostas ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE propostas ADD COLUMN IF NOT EXISTS deleted_by INTEGER;
ALTER TABLE propostas ADD COLUMN IF NOT EXISTS deletion_reason TEXT;

ALTER TABLE tarefas ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE tarefas ADD COLUMN IF NOT EXISTS deleted_by INTEGER;
ALTER TABLE tarefas ADD COLUMN IF NOT EXISTS deletion_reason TEXT;

ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS deleted_by INTEGER;
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS deletion_reason TEXT;

ALTER TABLE consents ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE consents ADD COLUMN IF NOT EXISTS deleted_by INTEGER;
ALTER TABLE consents ADD COLUMN IF NOT EXISTS deletion_reason TEXT;
ALTER TABLE consents ADD COLUMN IF NOT EXISTS purpose VARCHAR(120);
ALTER TABLE consents ADD COLUMN IF NOT EXISTS status VARCHAR(40);
ALTER TABLE consents ADD COLUMN IF NOT EXISTS revoked_by INTEGER;
ALTER TABLE consents ADD COLUMN IF NOT EXISTS metadata_json TEXT;

ALTER TABLE simulations ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE simulations ADD COLUMN IF NOT EXISTS deleted_by INTEGER;
ALTER TABLE simulations ADD COLUMN IF NOT EXISTS deletion_reason TEXT;

CREATE TABLE IF NOT EXISTS backup_audit_logs (
  id SERIAL PRIMARY KEY,
  operation VARCHAR(40) NOT NULL,
  target VARCHAR(160) NOT NULL,
  status VARCHAR(40) NOT NULL,
  checksum VARCHAR(128),
  metadata_json TEXT,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ
);
